/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteRouteImport } from './routes/workout/route'
import { Route as RideRouteRouteImport } from './routes/ride/route'
import { Route as PlanRouteRouteImport } from './routes/plan/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as RideIndexRouteImport } from './routes/ride/index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as WorkoutIdRouteImport } from './routes/workout/$id'
import { Route as RideGameIdRouteImport } from './routes/ride/$gameId'
import { Route as PlanIdRouteImport } from './routes/plan/$id'

const WorkoutRouteRoute = WorkoutRouteRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRouteRoute = RideRouteRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRouteRoute = PlanRouteRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutRouteRoute,
} as any)
const RideIndexRoute = RideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RideRouteRoute,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanRouteRoute,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutRouteRoute,
} as any)
const RideGameIdRoute = RideGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => RideRouteRoute,
} as any)
const PlanIdRoute = PlanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlanRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plan': typeof PlanRouteRouteWithChildren
  '/ride': typeof RideRouteRouteWithChildren
  '/workout': typeof WorkoutRouteRouteWithChildren
  '/plan/$id': typeof PlanIdRoute
  '/ride/$gameId': typeof RideGameIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/plan/': typeof PlanIndexRoute
  '/ride/': typeof RideIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plan/$id': typeof PlanIdRoute
  '/ride/$gameId': typeof RideGameIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/plan': typeof PlanIndexRoute
  '/ride': typeof RideIndexRoute
  '/workout': typeof WorkoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plan': typeof PlanRouteRouteWithChildren
  '/ride': typeof RideRouteRouteWithChildren
  '/workout': typeof WorkoutRouteRouteWithChildren
  '/plan/$id': typeof PlanIdRoute
  '/ride/$gameId': typeof RideGameIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/plan/': typeof PlanIndexRoute
  '/ride/': typeof RideIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plan'
    | '/ride'
    | '/workout'
    | '/plan/$id'
    | '/ride/$gameId'
    | '/workout/$id'
    | '/plan/'
    | '/ride/'
    | '/workout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plan/$id'
    | '/ride/$gameId'
    | '/workout/$id'
    | '/plan'
    | '/ride'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/plan'
    | '/ride'
    | '/workout'
    | '/plan/$id'
    | '/ride/$gameId'
    | '/workout/$id'
    | '/plan/'
    | '/ride/'
    | '/workout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanRouteRoute: typeof PlanRouteRouteWithChildren
  RideRouteRoute: typeof RideRouteRouteWithChildren
  WorkoutRouteRoute: typeof WorkoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof WorkoutRouteRoute
    }
    '/ride/': {
      id: '/ride/'
      path: '/'
      fullPath: '/ride/'
      preLoaderRoute: typeof RideIndexRouteImport
      parentRoute: typeof RideRouteRoute
    }
    '/plan/': {
      id: '/plan/'
      path: '/'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof PlanRouteRoute
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof WorkoutRouteRoute
    }
    '/ride/$gameId': {
      id: '/ride/$gameId'
      path: '/$gameId'
      fullPath: '/ride/$gameId'
      preLoaderRoute: typeof RideGameIdRouteImport
      parentRoute: typeof RideRouteRoute
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdRouteImport
      parentRoute: typeof PlanRouteRoute
    }
  }
}

interface PlanRouteRouteChildren {
  PlanIdRoute: typeof PlanIdRoute
  PlanIndexRoute: typeof PlanIndexRoute
}

const PlanRouteRouteChildren: PlanRouteRouteChildren = {
  PlanIdRoute: PlanIdRoute,
  PlanIndexRoute: PlanIndexRoute,
}

const PlanRouteRouteWithChildren = PlanRouteRoute._addFileChildren(
  PlanRouteRouteChildren,
)

interface RideRouteRouteChildren {
  RideGameIdRoute: typeof RideGameIdRoute
  RideIndexRoute: typeof RideIndexRoute
}

const RideRouteRouteChildren: RideRouteRouteChildren = {
  RideGameIdRoute: RideGameIdRoute,
  RideIndexRoute: RideIndexRoute,
}

const RideRouteRouteWithChildren = RideRouteRoute._addFileChildren(
  RideRouteRouteChildren,
)

interface WorkoutRouteRouteChildren {
  WorkoutIdRoute: typeof WorkoutIdRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
}

const WorkoutRouteRouteChildren: WorkoutRouteRouteChildren = {
  WorkoutIdRoute: WorkoutIdRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
}

const WorkoutRouteRouteWithChildren = WorkoutRouteRoute._addFileChildren(
  WorkoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanRouteRoute: PlanRouteRouteWithChildren,
  RideRouteRoute: RideRouteRouteWithChildren,
  WorkoutRouteRoute: WorkoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
