/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RideRouteImport } from './routes/ride'
import { Route as WorkoutRouteRouteImport } from './routes/workout/route'
import { Route as PlanRouteRouteImport } from './routes/plan/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as WorkoutIdRouteImport } from './routes/workout/$id'
import { Route as PlanIdRouteImport } from './routes/plan/$id'

const RideRoute = RideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRouteRoute = WorkoutRouteRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRouteRoute = PlanRouteRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutRouteRoute,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanRouteRoute,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutRouteRoute,
} as any)
const PlanIdRoute = PlanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlanRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plan': typeof PlanRouteRouteWithChildren
  '/workout': typeof WorkoutRouteRouteWithChildren
  '/ride': typeof RideRoute
  '/plan/$id': typeof PlanIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/plan/': typeof PlanIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ride': typeof RideRoute
  '/plan/$id': typeof PlanIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/plan': typeof PlanIndexRoute
  '/workout': typeof WorkoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plan': typeof PlanRouteRouteWithChildren
  '/workout': typeof WorkoutRouteRouteWithChildren
  '/ride': typeof RideRoute
  '/plan/$id': typeof PlanIdRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/plan/': typeof PlanIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plan'
    | '/workout'
    | '/ride'
    | '/plan/$id'
    | '/workout/$id'
    | '/plan/'
    | '/workout/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ride' | '/plan/$id' | '/workout/$id' | '/plan' | '/workout'
  id:
    | '__root__'
    | '/'
    | '/plan'
    | '/workout'
    | '/ride'
    | '/plan/$id'
    | '/workout/$id'
    | '/plan/'
    | '/workout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanRouteRoute: typeof PlanRouteRouteWithChildren
  WorkoutRouteRoute: typeof WorkoutRouteRouteWithChildren
  RideRoute: typeof RideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof WorkoutRouteRoute
    }
    '/plan/': {
      id: '/plan/'
      path: '/'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof PlanRouteRoute
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof WorkoutRouteRoute
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdRouteImport
      parentRoute: typeof PlanRouteRoute
    }
  }
}

interface PlanRouteRouteChildren {
  PlanIdRoute: typeof PlanIdRoute
  PlanIndexRoute: typeof PlanIndexRoute
}

const PlanRouteRouteChildren: PlanRouteRouteChildren = {
  PlanIdRoute: PlanIdRoute,
  PlanIndexRoute: PlanIndexRoute,
}

const PlanRouteRouteWithChildren = PlanRouteRoute._addFileChildren(
  PlanRouteRouteChildren,
)

interface WorkoutRouteRouteChildren {
  WorkoutIdRoute: typeof WorkoutIdRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
}

const WorkoutRouteRouteChildren: WorkoutRouteRouteChildren = {
  WorkoutIdRoute: WorkoutIdRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
}

const WorkoutRouteRouteWithChildren = WorkoutRouteRoute._addFileChildren(
  WorkoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanRouteRoute: PlanRouteRouteWithChildren,
  WorkoutRouteRoute: WorkoutRouteRouteWithChildren,
  RideRoute: RideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
