/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteRouteImport } from './routes/workout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as WorkoutIdRouteImport } from './routes/workout/$id'

const WorkoutRouteRoute = WorkoutRouteRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutRouteRoute,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workout': typeof WorkoutRouteRouteWithChildren
  '/workout/$id': typeof WorkoutIdRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/workout': typeof WorkoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workout': typeof WorkoutRouteRouteWithChildren
  '/workout/$id': typeof WorkoutIdRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workout' | '/workout/$id' | '/workout/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workout/$id' | '/workout'
  id: '__root__' | '/' | '/workout' | '/workout/$id' | '/workout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkoutRouteRoute: typeof WorkoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof WorkoutRouteRoute
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof WorkoutRouteRoute
    }
  }
}

interface WorkoutRouteRouteChildren {
  WorkoutIdRoute: typeof WorkoutIdRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
}

const WorkoutRouteRouteChildren: WorkoutRouteRouteChildren = {
  WorkoutIdRoute: WorkoutIdRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
}

const WorkoutRouteRouteWithChildren = WorkoutRouteRoute._addFileChildren(
  WorkoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkoutRouteRoute: WorkoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
